/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package zentech.application.form.other;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;
import javax.swing.SwingUtilities;

/**
 *
 * @author Duc Pham Ngoc
 */
public class WarehouseDesignForm extends javax.swing.JPanel {

    /**
     * Creates new form WarehouseDesignForm
     */
    private int mouseOffsetX, mouseOffsetY;
    public WarehouseDesignForm() {
        initComponents();
        setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
    }
    
    private void addNewDraggableLabel(Icon icon, int x, int y) {
        JLabel lbl = new JLabel(icon);
        lbl.setSize(icon.getIconWidth(), icon.getIconHeight());
        lbl.setLocation(x, y);
        lbl.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));

        // Tạo popup menu (Xoay, Xóa)
        JPopupMenu popup = new JPopupMenu();
        JMenuItem rotateItem = new JMenuItem("Xoay hình");
        JMenuItem deleteItem = new JMenuItem("Xóa");
        popup.add(rotateItem);
        popup.add(deleteItem);

        rotateItem.addActionListener(ae -> {
            Icon ic = lbl.getIcon();
            if (ic instanceof ImageIcon) {
                ImageIcon imgIcon = (ImageIcon) ic;
                Image img = imgIcon.getImage();
                int w = imgIcon.getIconWidth();
                int h = imgIcon.getIconHeight();
                BufferedImage buf = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
                Graphics2D g2 = buf.createGraphics();
                g2.drawImage(img, 0, 0, null);
                g2.dispose();
                BufferedImage rot = new BufferedImage(h, w, BufferedImage.TYPE_INT_ARGB);
                Graphics2D g2d = rot.createGraphics();
                g2d.translate((h - w) / 2, (h - w) / 2);
                g2d.rotate(Math.toRadians(90), w / 2.0, h / 2.0);
                g2d.drawImage(buf, 0, 0, null);
                g2d.dispose();
                lbl.setIcon(new ImageIcon(rot));
                lbl.setSize(rot.getWidth(), rot.getHeight());
            }
        });
        deleteItem.addActionListener(ae -> {
            jPanel1.remove(lbl);
            jPanel1.revalidate();
            jPanel1.repaint();
        });

        lbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    popup.show(lbl, e.getX(), e.getY());
                }
            }
            @Override
            public void mousePressed(MouseEvent e) {
                mouseOffsetX = e.getX();
                mouseOffsetY = e.getY();
                lbl.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            }
            @Override
            public void mouseReleased(MouseEvent e) {
                lbl.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
            }
        });
        lbl.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                int newX = lbl.getX() + e.getX() - mouseOffsetX;
                int newY = lbl.getY() + e.getY() - mouseOffsetY;
                if (newX < 0) newX = 0;
                if (newY < 0) newY = 0;
                if (newX + lbl.getWidth() > jPanel1.getWidth()) {
                    newX = jPanel1.getWidth() - lbl.getWidth();
                }
                if (newY + lbl.getHeight() > jPanel1.getHeight()) {
                    newY = jPanel1.getHeight() - lbl.getHeight();
                }
                lbl.setLocation(newX, newY);
            }
        });
        
        jPanel1.add(lbl);
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();

        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("jLabel1");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        canvas1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int newX = jLabel1.getX() + evt.getY() - mouseOffsetX;
        int newY = jLabel1.getY() + evt.getY() - mouseOffsetY;
        
        if(newX < 0){
            newX = 0;
        }
        if(newY < 0){
            newY = 0;
        }
        
        int parentWidth = jPanel1.getWidth();
        int parentHeight = jPanel1.getHeight();
        if(newX + jLabel1.getWidth() > jPanel1.getWidth()){
            newX = jPanel1.getWidth() - jLabel1.getWidth();
        }
        if(newY + jLabel1.getHeight() > jPanel1.getHeight()){
            newY = jPanel1.getHeight() - jLabel1.getHeight();
        }
        jLabel1.setLocation(newX, newY);
        
        
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        mouseOffsetX = evt.getX();
        mouseOffsetY = evt.getY();
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(Color.red, 2));
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            Icon icon = jLabel1.getIcon();
            addNewDraggableLabel(icon, 10, 10);
        }
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
